### ISSUE TITLE
Authorization error with uploadFileCreateElement call 

### ISSUE THREAD

**Issue by ethan92429** [onshape-public/java-client#2]
@harmanpa it looks like the library errors out when attempting to uploadFileCreateElement. Here is the code:

```Java
@Test
public void testOnshape() throws Exception {
    Onshape onshape = new Onshape();
    String accessKey = "CENSORED";
    String secretKey = "CENSORED";
    onshape.setAPICredentials(accessKey, secretKey);
    BlobElementsUploadFileCreateElementRequest.Builder builder = onshape.blobElements().uploadFileCreateElement();
    builder.encodedFilename("bolt.SLDPRT");
    builder.file(new File("generic_file"));

    System.out.println(builder.call("DID", "WID").getName());
}
```

Would it be possible to add a test for this and to also investigate why it is not authorizing correctly?

**Comment by harmanpa** [comment]
Is the response a 400 Bad Request?

**Comment by ravinreddy** [comment]
I think user got Unauthorized error to start with, but I think that is legit error because of permissions to document. The user switched to our API Explorer to avoid permissions issues and try to inside a document. He got ECONNRESET. Do we have a test for this? Can we write a test to upload a small file?

**Comment by harmanpa** [comment]
I was receiving 400 Bad Requests with this method. Strangely I had had tests of one of the Translations methods (which is very similar) pass before, but it turns out the client wasn't creating the multipart form data correctly. Next time the build is run this will be fixed in the client thanks to https://github.com/onshape-public/api-generator/pull/13.

Subject to that fix, the following code can be used to create a new document and upload a file as a new element in it:

```
        File f = new File(<PATH_TO_FILE>);
        Onshape o = new Onshape();
        OnshapeDesktop od = new OnshapeDesktop(<ONSHAPE_CLIENTID>, <ONSHAPE_CLIENTSECRET>);
        od.setupClient(o);
        DocumentsCreateDocumentResponse createdDocument = o.documents().createDocument().isPublic(Boolean.TRUE).name(<DOCUMENT_NAME>).ownerType(0).call();
        BlobElementsUploadFileCreateElementResponse response = o.blobElements()
                .uploadFileCreateElement()
                .file(f)
                .translate(Boolean.TRUE)
                .yAxisIsUp(Boolean.FALSE)
                .flattenAssemblies(Boolean.FALSE)
                .call(createdDocument.getId(), createdDocument.getDefaultWorkspace().getId());
```

**Comment by ethan92429** [comment]
@harmanpa I built a new version but a customer is still running into the errors. OnshapeDesktop is hanging on the request, I believe. @ravinreddy, do you have more info about this?

**Comment by harmanpa** [comment]
I missed a vital bit of information on OnshapeDesktop - the associated app needs to be setup in the dev-portal to redirect to ``http://localhost:6789``. OnshapeDesktop is only for using OAuth via the desktop (which is useful for testing). Alternatively API keys can be used with ``o.setAPICredentials(<KEY>, <SECRET>)``.

**Comment by ethan92429** [comment]
@ravinreddy did you mention that you tried with the API credentials and were still experiencing issues?

**Comment by harmanpa** [comment]
@ravinreddy 
_Can you rewrite your sample not using OnshapeDesktop?_
Yes and I get Unauthorized too, on the uploadFileCreateElement call, even though the createDocument call is successful.

Do we know at what point the OnshapeDesktop.setupClient(...) call blocks? i.e. has the browser opened with the login window, and has the login been completed?

**Comment by harmanpa** [comment]
If it is incorrect that this method should be returning Unauthorized when using API keys, then the error would be either:
* The ``signature(...)`` method in the client is not creating the authorization headers correctly (though it is working for other methods):
https://github.com/onshape-public/api-generator/blob/4aebd70d4b22e018baa8558c36665d0351c4478f/onshape-java/api-base/src/main/java/com/onshape/api/base/BaseClient.java#L510
* There is another header required for POST methods, I believe XSRF is not currently required?

@ethan92429 ?

**Comment by ethan92429** [comment]
Correct, AFAIK, the XSRF token doesn't look required. Also, the signature looks fine, although I'd have to run it against my local stack to check. Are there instructions on how to set up and run the tests somewhere @harmanpa? That way I can test it against my local Onshape stack to see the errors.

**Comment by ethan92429** [comment]
@harmanpa where is the test that Jenkins runs to test this? Should it be [here](https://github.com/onshape-public/java-client/blob/master/src/test/java/com/onshape/api/DocumentsTest.java)? It looks like it isn't. Would it be possible to add that test?

**Comment by ethan92429** [comment]
I've been poking my local stack, and it looks like the content type that the signature maker is using to sign in the client is `application/json` in the client, and `multipart/form-data;boundary=boundary_1_687892306_1553621453803` in the client, which suggests that we need to grab the content-type header value after the boundary key gets made in order to sign the request properly. The issue with that is the boundary key gets made as part of the final request call, so there appears to be no way to access it in between making the call in the code, and Javax making the call. I'm looking into the Javax codebase to see if it's possible to break apart these calls.

**Comment by harmanpa** [comment]
Ah, it's probably this line then:
https://github.com/onshape-public/api-generator/blob/954998a8d21b012d8ea67a70c8d9efa119e8d901/onshape-java/api-base/src/main/java/com/onshape/api/base/BaseClient.java#L549

I'd not noticed that "application/json" is part of the signature data, does it just need to be changed to "multipart/form" if it's multipart?

**Comment by ethan92429** [comment]
It needs to be changed to `multipart/form-data;boundary=boundary_1_687892306_1553621453803`

**Comment by ethan92429** [comment]
Which is what Javax changes the Content-Type header to when you call `invocationBuilder.method()`

**Comment by ethan92429** [comment]
So I'm not quite sure how to get that randomly generate boundary key.

**Comment by ethan92429** [comment]
See [here](https://docs.oracle.com/javaee/7/api/javax/ws/rs/client/SyncInvoker.html#method-java.lang.String-javax.ws.rs.client.Entity-) the docs mention that it will change Content-Type based on the variant

**Comment by harmanpa** [comment]
There's an interface for registering an interceptor (https://jersey.github.io/apidocs-javax.jax-rs/2.0.1/index.html?javax/ws/rs/ext/WriterInterceptor.html), presumably this gets the final Entity and hence MediaType. I will look at moving the addition of the auth headers to use this.

**Comment by ethan92429** [comment]
Yeah, that's what it seems like we'll have to do. @ravinreddy is looking for an alternative solution - perhaps using the apache library.

**Comment by harmanpa** [comment]
In https://github.com/onshape-public/api-generator/pull/17 I've shifted the auth headers to be added after the entity has been prepared, so we know what the media-type is. While preparing the entity, the boundary subtype is added by using ``Boundary.addBoundary(MediaType mediaType)``. Even though this method will be called later by Jersey, it's implementation does not create a new boundary if one exists (https://github.com/eclipse-ee4j/jersey/blob/eafb9bdcb82dfa3fd76dd957d307b99d4a22c87f/media/multipart/src/main/java/org/glassfish/jersey/media/multipart/Boundary.java#L44).

WriterInterceptor was not the right answer, and in fact I tried that and it intercepts before the boundary was being added so is no help.

**Comment by ethan92429** [comment]
@harmanpa So with the new changes did that test pass?

**Comment by harmanpa** [comment]
Yes the test passes

**Comment by ethan92429** [comment]
Thanks Peter!

**Comment by ethan92429** [comment]
This should be fixed here: https://github.com/onshape-public/java-client/commit/4d64870e689c74ba014dced032e9a311f5b53d4a
