### ISSUE TITLE
getOrCreateBillOfMaterialsElement method returns serializer exception

### ISSUE THREAD

**Issue by poppiol** [onshape-public/java-client#26]
Hi,
When I use this code:
`OnshapeDocument document = new OnshapeDocument(documentId, workspaceId, elementId);
onshape.assemblies().getOrCreateBillOfMaterialsElement().call(document);`

I'm getting this exception:
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.onshape.api.requests.AssembliesGetOrCreateBillOfMaterialsElementRequest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)`

I'm not sure if I'm doing something wrong or this is actually an issue.
I'm getting expected results using API Explorer, but I cannot make it working using Java API.
Any help with using this endpoint would be appreciated.

**Comment by harmanpa** [comment]
This is caused by #19 - I also found this issue when attempting to access BoM tables. I have used the following workaround:
```
        JsonNode jsonBom = onshape.call("GET", "/assemblies/d/:did/[wvm]/:wvm/e/:eid/bom",
                null,
                onshape.buildMap("did", configuredAssembly.getDocumentId(),
                        "wvmType", configuredAssembly.getWvmType(),
                        "wvm", configuredAssembly.getWvmId(),
                        "eid", configuredAssembly.getElementId()),
                onshape.buildMap("indented", indented, "multiLevel", multiLevel),
                JsonNode.class);
        JsonNode bomTable = jsonBom.get("bomTable");
        JsonNode items = bomTable.get("items");
        JsonNode headers = bomTable.get("headers");
```

**Comment by poppiol** [comment]
Yes, that is also a nice workaround.
I solved the problem like this:

`AssembliesGetBillOfMaterialsResponse response = onshape.assemblies().getBillOfMaterials().indented(true).generateIfAbsent(true).call(document);`

Thank you.
