### ISSUE TITLE
Add pointing to another stack.

### ISSUE THREAD

**Issue by ethan92429** [onshape-public/java-client#3]
@harmanpa I'm trying to test the upload blob code against my local stack at localhost:8080. Does your client support setting the baseURL dynamically rather than hardcoding it? I see it is hardcoded [here](https://github.com/onshape-public/java-client/blob/ba504929a033e1efdd5be025f1cfe7d7374ad658/src/main/java/com/onshape/api/base/BaseClient.java#L80) Maybe the value could default to that, and we just expose a setBaseURL() method for setting it?

**Comment by harmanpa** [comment]
Oops Github got over excited and closed issue. Issue will be closed when build is run.

**Comment by ethan92429** [comment]
Fixed here: https://github.com/onshape-public/java-client/commit/4d64870e689c74ba014dced032e9a311f5b53d4a
